---
  - name: add postgres apt repo key
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: add postgres apt repo
    apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main"
                    state=present

  - name: install postgres
    apt: pkg={{ item }} state=installed
    with_items:
      - postgresql-9.3
      - postgresql-server-dev-9.3

  - name: install psycopg2
    easy_install: name=psycopg2

  - name: create db
    postgresql_db: name={{ db_name }}
                    encoding='UTF-8'
                    lc_collate='en_GB.UTF-8'
                    lc_ctype='en_GB.UTF-8'
                    template='template0'
    sudo: yes
    sudo_user: postgres

  - name: create postgresql user
    postgresql_user: db={{ db_name }}
                     user={{ db_user }}
                     password={{ db_password }}
                     role_attr_flags=SUPERUSER
    sudo: yes
    sudo_user: postgres

  - name: update postgresql.conf
    copy: src=postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf
    notify:
      - restart postgresql

  - name: update postgres hba.conf
    copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
    notify:
      - restart postgresql
